import Head from 'next/head'
import Dasboard from '../components/Dasboard'
import Auth from '../components/Auth/Auth'
import { GetServerSideProps } from 'next'


export default function Home(props:any) {

  const {authorized} = props

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {authorized ? <Dasboard/> : <Auth/>}
  
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const jwt = ctx.req.cookies.token;

  // if (jwt) 
  //   return { 
  //     props: {
  //       authorized: true,
  //     },
  //   };
  
  return {
    props: {
      authorized: jwt ? true : false,
    },
  };
}
